### ISSUE TITLE
Will there be pytorch version?

### ISSUE THREAD

**Issue by brandnew2017** [jpsml/6-DOF-Inertial-Odometry#2]
Looking forward to your reply. Thank you very much.

**Comment by BarzelS** [comment]
> Looking forward to your reply. Thank you very much.

Hi @brandnew2017, have you managed to find a torch version?
Thanks

**Comment by brandnew2017** [comment]
Sorry, I haven't find a torch version.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jpsml/6-DOF-Inertial-Odometry"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月25日(星期二) 下午4:28
收件人:&nbsp;"jpsml/6-DOF-Inertial-Odometry"<6-DOF-Inertial-Odometry@noreply.github.com&gt;;
抄送:&nbsp;"刘丽"<1242840732@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [jpsml/6-DOF-Inertial-Odometry] Will there be pytorch version? (#2)





  
Looking forward to your reply. Thank you very much.
  
Hi @brandnew2017, have you managed to find a torch version?
 Thanks

**Comment by jpsml** [comment]
Hi, @brandnew2017, unfortunately there is no plan for a PyTorch version.
