### ISSUE TITLE
Version in Prerequisites

### ISSUE THREAD

**Issue by bryanbocao** [jpsml/6-DOF-Inertial-Odometry#4]
Dear authors, thanks for this great work. It would be great if we have the version for the prerequisites, specifically
```
Python 3
TensorFlow
Keras
NumPy
Matplotlib
scikit-learn
Pandas
SciPy
numpy-quaternion
tfquaternion
```
Thanks!

**Comment by bryanbocao** [comment]
Found that in the provided paper.
```
Keras (https://keras.io/) 2.2.4
together with TensorFlow (https://www.tensorflow.org/) 1.13.1
```
Thanks!

**Comment by JayKarhade** [comment]
Can you please mention the versions of all the libraries in case you were able to run the files?
