### ISSUE TITLE
Requirements version incompatibility

### ISSUE THREAD

**Issue by patrickctrf** [jpsml/6-DOF-Inertial-Odometry#6]
Hi!

I am trying to reproduce your results, but cannot find requirements version, and this is leading to several bugs while running train and test scripts (testing with pretrained models).

Can you provide keras and tensorflow versions that support this code?

Thanks!

**Comment by jpsml** [comment]
Keras 2.2.4
TensorFlow 1.13.1

Em qui, 19 de ago de 2021 17:04, Patrick Ferreira ***@***.***>
escreveu:

**Comment by c53wei** [comment]
Hi there! I am also wondering if you could provide the requirements.txt? I am having trouble reproducing your results as a lot packages have been changed since then. Thank you!

**Comment by ProjektgruppeSDF** [comment]
@c53wei  Hello! I am facing the same problem and could not yet successfully train the model. If you found a working combination of package versions, I would be grateful if you shared it.

**Comment by c53wei** [comment]
@ProjektgruppeSDF I haven't looked at this in a while but in my notes I seem to have the following package versions:

python 3.7
tensorflow 1.13.1
keras 2.2.4
numpy 1.20.3
scikit-learn 0.20.3 or 0.20.4
pandas 0.24.2
scipy 1.2.2
numpy-quaternion 2019.7.3.22.46.7
tf quaternion ?
matplotlib 3.1.1
protobuf 3.20.3
numba 0.43.1
llvmlite 0.20.0
h5py 2.9.0

Hope this helps someone
